### ISSUE TITLE
Feature request for time-based zone assignment

### ISSUE THREAD

**Issue by 3154** [FluffierThanThou/ColonyManager#100]
Apologies, but I have a feature request.

Since Colony Manager came to be, running a farm is no longer a micromanagement nightmare. I am fine with adjusting zones just twice - at the start and end of _grazing season_. 

The final missing piece is some form of a time-based zone assignment. That will allow you to move your animals in a _safe place for the night_. You can already do it manually, but of course that is an impossibly dull task. Or maybe something that uses the sleeping spot logic, only it is more of a sleeping zone.

For the love of all Muffalos slain in their sleep, please consider it.

**Comment by FluffierThanThou** [comment]
I'm not too keen on adding a time mechanic, as the rest of the manager setup is not aware of time. It also wouldn't work reliably without setting the job to a low update interval.

I'm curious though, why not just put a barn building with animal sleeping spots in the allowed zone? The animals should look up a sleeping spot by themselves, and go into the barn on their own?

**Comment by 3154** [comment]
Because I'm stupid. Well, dropping 100 sleeping spots ain't pretty, but I can do it. Thanks!
