### ISSUE TITLE
Adjust power tab number truncating and rounding.

### ISSUE THREAD

**Issue by ForsakenShell** [FluffierThanThou/ColonyManager#110]
The power tab has a small issue where it adjusts the unit type too early such that it value is too small to be meaningfully accurate.

ie:  Generating 100KW of power will be displayed as 0.1MW.  This is seemingly good however, it will show 0.1MW up until 200kW of power is generated when it becomes 0.2MW.  The issue is that these values do not reflect the actual amount of power and may be off as much as 50% (showing 0.1MW for 199.9KW) for lower values of the unit type.

I propose not moving up a unit until at least a whole unit of that type is reached.  For example, I would rather know I am generating 275.6KW of power then 0.2MW.  It is more meaningful and useful.

**Comment by FluffierThanThou** [comment]
you're alive! 🤗 

And yeah, that sounds reasonanble. I'll see what I can do.
