### ISSUE TITLE
Pregnant slaughter

### ISSUE THREAD

**Issue by CecilFF4** [FluffierThanThou/ColonyManager#121]
Running beta 0.18, colony manager v0.18.3.3. I know it isn't an updated version, but I didn't see any fix in later versions for pregnant animals being slaughtered when the check box for pregnant was deselected. Just had a pregnant muffalo (middle-stage, 3 years old, healthy) get slaughtered.

I got a lot of other mods going on in this, but I've never encountered any conflicts. I doubt you'll be able to load my saves, but I uploaded my manual save from after the slaughter and one auto-save from before. Just rename the txt file to rar to open it.

[Saves.txt](https://github.com/FluffierThanThou/ColonyManager/files/2238124/Saves.txt)

**Comment by FluffierThanThou** [comment]
sorry it took me so long, but I can confirm that this works as expected with just Colony Manager. I doubt there's a mod conflict for something so basic, so I have no idea what happened. Are you sure you didn't misunderstand the options, and _enabled_ slaughtering pregnant animals by accident?

**Comment by CecilFF4** [comment]
I appreciate you looking into it. So far, it was just a one-time thing and I've never enabled preg slaughtering on any save. If it happens again, I'll let you know. Again, thanks.
