### ISSUE TITLE
Research Options don't Display Correctly

### ISSUE THREAD

**Issue by serenewaffles** [FluffierThanThou/ColonyManager#124]
I'm not sure if this is a bug or because of other mods or my mod list, but the research options for the manager don't line up in the tree correctly. I am using the following mods (in load order) and have attached a screen shot of the layout. I couldn't find anything in the documentation about mod load order to test if that is the issue.

1. Core
1. HugsLib
1. EdB Prepare Carefully
1. Prepare Landing
1. Colony Manager
1. RT Fuse
1. [KV] RimFridge - B19
1. Medical Tab
1. Hand Me That Brick Lite

Screenshot:
![image](https://user-images.githubusercontent.com/775693/46874418-207dac00-ce07-11e8-9885-2d52e8e5c6ef.png)

**Comment by tmajibon** [comment]
That's a really old problem and I think it gets ignored because there's a great mod that fixes it... Also from Fluffy!

https://github.com/FluffierThanThou/ResearchTree

**Comment by FluffierThanThou** [comment]
yeah... Pretty much what @tmajibon said. I really don't like the vanilla research UI. The manual placement of nodes especially is cumbersome, and whether it looks good depends entirely on which other mods you have loaded - so I don't even bother with it. Sorry about that!
