### ISSUE TITLE
Request: restrict animal area only once (upon taming)

### ISSUE THREAD

**Issue by CodeOptimist** [FluffierThanThou/ColonyManager#137]
I was wondering if animal area could be set just _once_ after taming. Right now it does an excellent job of setting their area restriction, but then I will adjust this later (e.g. pull animals into base during a Raid), only to have this overridden the next time a pawn manages - sending my animals back out into danger.

Love this mod; used it for a long time now.

(Edit: Actually, I might work on this.)

**Comment by FluffierThanThou** [comment]
Possible, sure. I'd welcome pull requests, but I should warn you that it's probably going to be more tricky than it sounds. The manager is currently essentially stateless, it doesn't care of keep track of which animals are doing what.
