### ISSUE TITLE
Enhancement: population culling

### ISSUE THREAD

**Issue by jtgibson01** [FluffierThanThou/ColonyManager#138]
Sometimes it would be nice to kill animals that are overpopulated or that pose a risk to colonists if their population counts get too large (more likely with mods, not necessarily as likely in vanilla, like Walking Problem's unfortunately-named-but-quite-innocent Wild Animal Sex).

Being able to cull animals can be hacked around by setting the desired resource to some kind of meat you'll know you'll never have in your colony even once in a blue moon (like Genetic Rim spliced meats) and setting the desired count manually as high as it will go.  The next time the manager goes to the desk, literally every one of the vermin will be designated.  Unfortunately, there are two problems with this approach:
* It requires either complex math to try to decide how much meat you want to designate, as well as some sort of means of counting all the animals across the map (with honourable mention of the very very useful and popular Allow Tool mod by a certain special author...), or requires you to say 'Screw it, we'll kill 'em all'.  This obviates the purpose of using a manager job to handle the population, more or less compelling a direct, hands-on, manually drafted [emu war](https://en.wikipedia.org/wiki/Emu_War) with pretty much guaranteed failure.
* When a hunter kills the animal with a hunting job, they will automatically haul it back to a stockpile zone as per normal hunting behaviour.  This takes up too much time when the animal population is spiralling out of control.  The colony needs to be able to forbid hauling of corpses of particular verminous animals, at least until the population falls within more manageable limits.  (This can technically be worked around by temporarily removing that creature type from all allowed stockpiles, but forgetting to put it back can result in some unpleasantness.)

Adding the ability to limit wild populations while keeping them wild still could be accomplished with a few features on the Hunting tab:

* A selector that toggles between "Stockpile" mode (the current target count mode) which counts stockpiled resources versus total designated meat amounts, versus "Population" mode which specifies the desired limits of animals in the wild -- normally set to 0/0 for minima and 1000/1000 for maxima.  (As the Livestock tab already maintains live counts of wild animals, this would not add much extra burden to the processing.)  This would be generally useful, not just for culling -- for instance, it'd also be useful for automatically designating lone thrumbos as soon as they arrive, etc.

* Two fields to specify minimum populations of males and females to keep, so that overzealous hunters do not depress the population.  Manager designations would not designate additional animals of a sex beyond this limits, choosing only the other sex -- or skipping further designations entirely if that sex is also at its limit.  This would also be generally useful, not just for culling -- for instance, hunting bucks before hunting does ("bros before does" --Elliot, _Open Season_).

* "Cull as vermin (forbid, do not haul/butcher)" checkbox that will auto-forbid any animals of the matching types that die for any reason (requires prefix/postfix wrapper of Pawn.Kill that checks for the existence of a hunt designation and a corresponding managing job upon animal death).  This would be specific to culling.  The logical inverse of the Unforbid corpses option that already exists, and mutually exclusive with it, so checking Unforbid would disable Cull and vice versa, but both may be left unchecked if desired (a three-state toggle -- Unforbid, Off, or Cull -- with two checkboxes).

* Perhaps a checkbox that also allows designating live but wounded or ill animals before designating healthy animals, prioritising simply based on the combined number of hediffs they possess.  This too would be generally useful, not just for culling -- to encourage hunters to finish the job, etc.  (The opposite could be added as another mutually-exclusive checkbox, too, in case you're a vindictive person who wants to leave wounded and sick animals alone and go after the healthy ones first.)

**Comment by FluffierThanThou** [comment]
Thanks for the well thought out proposal. My apologies that it took me so long to respond.

I have a few questions/counterpoints I'd like your opinion on;
 - When my colony grows to be a certain size, I tend to secure the local area by assigning a hunting job similar to what you're describing; an unattainable threshold, and hunt all predators (or otherwise undesirables). It appears to me that the important part is keeping predators away from an area, not necessarily limiting their numbers.
 - You mention vermin count growing out of control. To the best of my knowledge, the game keeps track of an 'ideal' level of wildlife, and will occasionally introduce new animals by spontaneous generation to get back to that level. 
 - In a similar vein, the difference between the genders in wild animals is entirely cosmetic - they don't breed, nor do they lay eggs or give milk.

I'm not opposed to the idea of introducing a 'population control' option for hunting jobs (akin to the clear areas mode for forestry), but I'm wondering where some of the specifics of your proposal come from.

**Comment by jtgibson01** [comment]
Heh -- I mentioned:
> (more likely with mods, not necessarily as likely in vanilla, like Walking Problem's unfortunately-named-but-quite-innocent Wild Animal Sex).

Wild Animal Sex is a currently-existing target for which vermin populations can explode -- small animals like vanilla rats or AnimalCollabProject guinea pigs can expand to Dwarf Fortress catsplosion levels without reaching the population limit, eventually causing deforestation.

The proposal came about because I wanted to write a wild-animal population mod of my own that would evaluate population [i]trends[/i] instead (and introduce some requested features that others have asked for, like having herds that leave the map due to uninhabitable conditions migrate back when conditions stabilise, instead of generating entirely new herds).  I would also enable wildfowl to make nests and lay eggs, and enabling animals to reproduce, but that's a more distant target (and, given my general development schedule and life balance, possibly a non-existent one).

As I was doing up the design document, being able to control animal populations came up fairly high on my brainstorming.  After doing a brief draft on an interface and system of culling populations, it occurred to me that a system for [i]managing[/i] desired populations already existed elsewhere... and so, the suggestion was made. =)

**Comment by FluffierThanThou** [comment]
Right, that makes a lot of sense. I must've missed that part of the suggestion.
