### ISSUE TITLE
Won't work even without any mod + new save

### ISSUE THREAD

**Issue by ShiroTheSniper** [FluffierThanThou/ColonyManager#143]
Hi! I love your mod but can't make it work these days :(

- The manager tab opens
- Can set jobs
- Can give the management work priority

But I can't right-click the desk with a colonist. A colonist with ONLY the manage work won't flag as idle and will just wander around, never go to work.

I disabled all my mods, restarted the game, start a new game with and without HugsLib and always the same phenomenon. I did it 2-3 times with the same results.

Here's the files you'll need:
[https://gist.github.com/3865dc138ed54df98dcf3a5efd49a121](url)
[https://www.dropbox.com/s/fir8bf18zhgrg82/TestModColonyManager.rws?dl=0](url)

Thanks for your hard work! :)

**Comment by FluffierThanThou** [comment]
it's working fine, just be mindful of job update intervals;
![interval](https://i.imgur.com/hsB5BEg.gif)

That said, it should give some feedback on right-clicking the desk, I'll add that.

**Comment by FluffierThanThou** [comment]
Ok, I've added some feedback for why a 'right click job' fails;
![feedback](https://i.imgur.com/ix7hSnS.gif)
