### ISSUE TITLE
Multi line text in production tab cut off

### ISSUE THREAD

**Issue by Lafreakshow** [FluffierThanThou/ColonyManager#23]
As to be seen in the screenshot the text is cut off at the top and bottom for all bills where the line with the possible workstations is too long
![20160727011324_1](https://cloud.githubusercontent.com/assets/1574685/17158797/0ee1b7a6-5399-11e6-8fca-bc5d447e0127.jpg)

This happens without any other mods installed. Seen it so far only with the Tailoring tables but i can imagine it would happen anywhere.

**Comment by FluffierThanThou** [comment]
yeah this is a known issue I really need to sort out.
