### ISSUE TITLE
[Bug] Manager doesn't see Rabbits

### ISSUE THREAD

**Issue by deimos790** [FluffierThanThou/ColonyManager#32]
Manager doesn't see/recognize Wild or Tamed Rabbits. Been this way since at least A14 I believe.

**Comment by keastes** [comment]
I've only seen this happen when starting with an existing save then loading colony manager, never had it on a new save.

**Comment by FluffierThanThou** [comment]
probably related to non-biome animals not being shown, should be fixed.
