### ISSUE TITLE
Massive slowdown on any size map with suspended or active PRODUCTION jobs.

### ISSUE THREAD

**Issue by ParadoxSong** [FluffierThanThou/ColonyManager#39]
We can verify that these errors are playing some or the entire role in the production job slowdown. 
One of the reasons this is a problem, would be, for instance, if I am understanding this correctly, you run out of say, Smokeleaf to be processed. This is a big problem for people who use the jobs import/exporting feature especially as if you make a colony and save the jobs for a few stages of progress, you're going to suffer for that as your FPS will tank as soon as this is imported. 

I have realized upon actually opening the log, that when all production jobs are moving, there may be no slowdown, however, this would mean removing Butcher Creature and Make Kibble from the list of production jobs unless you can keep the meat and carcasses in constant supply.

[Rimworld Production Jobs save.zip](https://github.com/FluffierThanThou/RW_Manager/files/649165/Rimworld.Production.Jobs.save.zip)

**Comment by FluffierThanThou** [comment]
Does this still happen in A16? Could you provide me the output_log?

**Comment by ParadoxSong** [comment]
After a quick test on every map size, I can say that this appears fixed. Try importing a list of manager jobs in the early game though that include bills for objects you don't have yet. My guess is your mod will freak out, even if the jobs are switched to suspended. I can't continue testing for a day or two, but next time I start up Rimworld I'll try it if you haven't.

**Comment by ParadoxSong** [comment]
I realize I never got back to this.  I'm closing this issue, the production-specific issue just magically disappeared, and since we can't import manager saves from old alphas (or my manager saves disappeared) I haven't had a major slowdown since.  It might've had something to do with that, since in all my non A16 testing I was importing that manager save.
