### ISSUE TITLE
Only installed art is counted?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/ColonyManager#41]
Zappa 25 Dec @ 1:04pm  Delete
Hi Fluffy, I want to report a bug with production of Large Sculptures, i set it to produce 5 of them, but it only recognises installed art and not uninstalled in the stockpile. If you need anymore info let me know, happy holidays

**Comment by ParadoxSong** [comment]
Side note: Should installed art really be counted?

**Comment by FluffierThanThou** [comment]
no, it shouldn't be. On the other hand, production is now gone from the manager, so this issue  is obsolete.
