### ISSUE TITLE
Doesn't seem compatable with Work Tab?

### ISSUE THREAD

**Issue by 1n5aN1aC** [FluffierThanThou/ColonyManager#42]
I added your Work Tab mod to an existing Colony Manager save, and I can no longer open the colony manager tab correctly.

Instead, it just shows the tab with no buttons or anything, and the game slows down an incredible amount.

**Comment by 1n5aN1aC** [comment]
I can further confirm that this appears to happen on a new save as well, with both mods enabled.

...the manager tab seems to revert back to just showing current jobs & manager skills, and not let you manage them, even when you have colonists assigned to the managing role & a managers desk.

I have HugsLib enabled as the first mod I load after core.

**Comment by FluffierThanThou** [comment]
Can't replicate. Please provide an output_log, closing for now.
