### ISSUE TITLE
Typo when colonist uses the manager desk "Conolony"

### ISSUE THREAD

**Issue by Deliphin** [FluffierThanThou/ColonyManager#43]
When a colonist leaves to go use the manager desk, it says "Doing essential **conolony** management at wooden basic manager desk."

Screenshot posted for evidence.

![conolony](https://cloud.githubusercontent.com/assets/14265753/21575661/74c7e3f2-ceea-11e6-88dc-31cb4d0a5d05.png)

**Comment by FluffierThanThou** [comment]
Duplicate of #29. I really should fix this soon.
