### ISSUE TITLE
patch for adding to existing games

### ISSUE THREAD

**Issue by Joshwoo70** [FluffierThanThou/ColonyManager#44]
what the titles says.

**Comment by Deliphin** [comment]
From the [Ludeon.com post](https://ludeon.com/forums/index.php?topic=16423.0) for this mod: 

> Requires a new save. Adds a worktype, which in my tests gave errors on old savegames.

There's a reason why this mod can't be added to existing games. It's because of the new "Manager" skill. The only way to fix it as far as I'm aware would be to remove that skill.

**Comment by FluffierThanThou** [comment]
I think in my latest tests (which were A15) it actually works fine with vanilla, it's with my own Work Tab that things break down. I'll have to investigate if that is the case, but if it is I will look into creating a workaround.

**Comment by FluffierThanThou** [comment]
Manager skill is gone!
