### ISSUE TITLE
Game freeze during foresty

### ISSUE THREAD

**Issue by Silerra** [FluffierThanThou/ColonyManager#45]
The game freeze for 3 to 5 seconds when the manager marking plants to cut or trees to foresting.
Is there a solution to work around this problem? These freezes are very annoying with time.

**Comment by FluffierThanThou** [comment]
If you're getting freezes that long, it's likely there's errors being produced somewhere. Under normal circumstances the jobs shouldn't cause such problems.

Either way, please provide me an output_log and save game.

**Comment by Silerra** [comment]
[output_log.txt](https://github.com/FluffierThanThou/ColonyManager/files/700273/output_log.txt)

[Rohan1 04.zip](https://github.com/FluffierThanThou/ColonyManager/files/700279/Rohan1.04.zip)

**Comment by ParadoxSong** [comment]
Sil, can you reproduce this bug in a save without other mods active?

**Comment by Silerra** [comment]
Oh sry, here the files from clean client:
[output_log.txt](https://github.com/FluffierThanThou/ColonyManager/files/713111/output_log.txt)
[New Eden 01.zip](https://github.com/FluffierThanThou/ColonyManager/files/713112/New.Eden.01.zip)

**Comment by FluffierThanThou** [comment]
hmm, nothing particularly interesting in that log... you're sure the pauses aren't because you're disconnecting and then reconnecting your joystick?

**Comment by Silerra** [comment]
So, I made a video to show what I actually mean here: https://youtu.be/CqP21Y38geY
In this video show a extreme situation. Which usually doesn't occur to this extent.

At beginning it's hardly noticeable since only small areas are present. But in mid- and lategame it becomes very noticeable.

And besides, I don't use a joystick in this game. My gamepad remain untouched. I use only my mouse and keyboard for Rimworld.

**Comment by FluffierThanThou** [comment]
ok, I can see that that's taking too long. On the other hand, you're setting a massive area of jungle to be cleared of all vegetation, which means it has to go through a pretty darn big amount of designations.

**Comment by FluffierThanThou** [comment]
ok, I can see that that's taking too long. On the other hand, you're setting a massive area of jungle to be cleared of all vegetation, which means it has to go through a pretty darn big amount of designations.

**Comment by FluffierThanThou** [comment]
ok I've tested this a bit ingame, the first time still takes quite a while (a consequence of all the safety checks), but when the job is then repeated it takes a lot less long for each iteration.

I'm afraid this is the best I can do without setting up a rather complicated cache mechanism, which I'm not too keep on.
