### ISSUE TITLE
Hysteresis for jobs

### ISSUE THREAD

**Issue by paranox** [FluffierThanThou/ColonyManager#46]
This is especially for cooking bills. When you define a threshold of less than X, you sometimes only get the cook producing 1 meal and then scurrying off to another job. Then repeats right after, causing unnecessary time spent on moving between jobs.

Please add a feature to define a repeat option so that when that trigger condition is met, the bill will be repeated Y times (like when adding bills manually) to make sure it doesn't trigger again just 10 seconds later.

**Comment by FluffierThanThou** [comment]
In essence this is hysteresis proposed in #20. 

It's something I've been wanting to do for a long time, but which would require quite a bit of refactoring.

**Comment by FluffierThanThou** [comment]
Because of changes in A17, many bugs in the production tab, and a general feeling that the production tab was slightly clumsy, I've removed it for A17 - I'll add most of it's functionality to an upcoming new mod, so stay tuned!
