### ISSUE TITLE
Mass duplication of bills at workbenches

### ISSUE THREAD

**Issue by Pichu0102** [FluffierThanThou/ColonyManager#52]
Many copies of bills are being made at workbenches. See https://ludeon.com/forums/index.php?topic=16120.msg290298#msg290298

**Comment by FluffierThanThou** [comment]
Thanks for reporting! Please provide an output_log so I can figure out what exactly is going on. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by Pichu0102** [comment]
Can't manage to reproduce yet. Will update when I find it again.

**Comment by Richard333** [comment]
Not sure if it's the same thing as what Pichu is talking about but I got some bug regarding the same thing of mass job bill duplication. 

Upon loading my save, even if there are bills with 0 to be done and/or ones with any number of times to be done another batch of bills will be added when someone uses the manager table. However though if someone uses the manager table again to add another batch of stuff to be done it'll just apply it to the bills that were created this time.

[output_log.txt](https://github.com/FluffierThanThou/ColonyManager/files/705710/output_log.txt)

**Comment by naanselmo** [comment]
Same thing happens to me as what @Richard333 is describing. I manually purge the 0 bills every now and then to stop it from happening since I'll have to scroll before active bills show up.

**Comment by Richard333** [comment]
Thought I'd go check to see how much my small amount of bills would add to the size of the save. 1 duplication of it added about 40-50kb. Some other interesting stuff I found. It only happens when they go to do it automatically. If you prioritize them to do it then it seems like it doesn't add any duplications. So it may be a result of some bug into them going to auto manage.

**Comment by naanselmo** [comment]
@Richard333 not happening when its forced may be related to issue #56

**Comment by Richard333** [comment]
@naanselmo re-adjusted some of my bills in priority and can confirm the bug you have as well as confirm that it doesn't add duplications when they're told to go manage. It also looks like upon loading they'll start from the first bill on the list when prioritized.

**Comment by Pichu0102** [comment]
After a load, it also will not clear old bills at stations if you delete them from the manager. Any bills made during the current play session will be deleted, however. Maybe the manager is forgetting which bills it owns and thinks old bills are manual bills on load?

Log:
https://gist.github.com/HugsLibRecordKeeper/4868e8758f9ea3c6981cce7e06e5833c

**Comment by FluffierThanThou** [comment]
Thanks for all the reports folks! Because of changes in A17, many bugs in the production tab, and a general feeling that the production tab was slightly clumsy, I've removed it for A17 - I'll add most of it's functionality to an upcoming new mod, so stay tuned!
