### ISSUE TITLE
Also don't count insect meat

### ISSUE THREAD

**Issue by frenchiveruti** [FluffierThanThou/ColonyManager#53]
Actually we have the option to untick "human meat", it would be nice to have one for insect meat too, as it seems to have a debuff in mood if used in meals.

**Comment by FluffierThanThou** [comment]
huh, is that a new thing?

I might just expand the tickbox to apply to all meat with a debuff attached to it, I don't want to add too much clutter.

In the mean time, you can always click the little loop next to the threshold to finetune it to your demands.

**Comment by frenchiveruti** [comment]
Here's the attachment to prove it.
![insect meat](https://cloud.githubusercontent.com/assets/1095997/22652208/614c56ae-ec64-11e6-9d2f-31c443ce68f9.png)
