### ISSUE TITLE
forcing colonist to work at desk should make them work until the queue is done

### ISSUE THREAD

**Issue by naanselmo** [FluffierThanThou/ColonyManager#56]
I've been hunting what I thought was a bug for a while, but now it seems like it may be an undesired "feature", where someone assigned to managing will only add one bill at a time. No matter how much work there is to be done, they'll add one bill at a time, and it'll start at the top and progress to the bottom of the list.

If I set that person with maximum priority on Managing, so that they willingly do the job, they'll add everything in a row without any issues, but if I force them to work they'll only add the first item on the list to be processed and then leave to do something else.

My managers literally don't stay there long enough for me to pause with them on the manager table if I force them to work, so I'm guessing they've been just walking there, creating a high priority production job that they're also assigned to do, and leaving before finishing managing.

I'd suggest changing it so that when forcing someone to manage they'd process everything rather than getting there and instantly leaving, having only applied the first job (which they then go on to do). Either that, or forcing them to stay there for at least one second or something like that.

Also, unrelated, I tried saving the manager jobs and then loading them, and I started getting lots of errors ([debug log](https://gist.github.com/57e8fca6c8e7eaffcf8a54986fd3e344)). Should I make a separate issue for this? Or is it mod incompatibility?

**Comment by FluffierThanThou** [comment]
You're right, this is by design. Having them do multiple bills on forced work is a good idea though, I'll look into that.

As for the import/export issue, please make a new ticket, and add the log + the exported jobs. You can find the exported jobs in the same place as save games.

**Comment by FluffierThanThou** [comment]
the import/export tab is going to get overhauled, I've disabled it for now.
