### ISSUE TITLE
Corpse counting in Manager

### ISSUE THREAD

**Issue by Andkovsted** [FluffierThanThou/ColonyManager#57]
The manager counts potential meat to avoid making too many hunting designations.
If you ask "hunting" to hunt when animal corpse > 5 it will designate one hunt, then count the meat as potential corpses or whatever you designate (leather for example). 
It then stops making more designations even if you only get one corpse until the animal has been killed.
it should be making 3 hunting designations if you lack 3 corpses (instead if one)

**Comment by FluffierThanThou** [comment]
I see your point... I'll look into it!
