### ISSUE TITLE
Pawn forced into job issue

### ISSUE THREAD

**Issue by MGuffin** [FluffierThanThou/ColonyManager#58]
v0.16.1.5

I am not 100% sure the issue from the mod alone, but does colony manager can "Force a pawn into job"?)

I sometimes get hunters that are stuck in their hunting job because they can't kill the target, (for example the target is asleep and can't get hit easily), then they keep shooting for hours until they collapses from fatigue. When I look at their status they are all "forced to hunt", and I am pretty sure I didnt do that myself.

(sorry for my english ;) )

**Comment by FluffierThanThou** [comment]
wasn't me either! 

(the manager only creates designations, it never tells specific pawns to do anything)
