### ISSUE TITLE
colonists ignore designations for managed jobs

### ISSUE THREAD

**Issue by eyemessiah** [FluffierThanThou/ColonyManager#60]
I'm playing the steam version of RW, with several fluffy mods + edb prepare carefully.

In a fairly new game Colony Manager was working briefly but then I noticed that foraging, logging & hunting all stalled inexplicably.   I deleted the CM jobs and & undesignated some trees and set an available to pawn to only cut plants but they still insist on idling.  I can't even right click on a designated tree to prioritise the job - the right click menu has vanished.  Starting a new game with CM disabled seems to resolve the issue (but I can't load my existing save without CM enabled so can't test that).

Any suggestions for rescuing this game?

**Comment by FluffierThanThou** [comment]
Thanks for reporting! Please provide an output_log so I can figure out what exactly is going on. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by FluffierThanThou** [comment]
closed because inactive
