### ISSUE TITLE
I think there are little bug.

### ISSUE THREAD

**Issue by a2755** [FluffierThanThou/ColonyManager#65]
[ModsConfig.zip](https://github.com/FluffierThanThou/ColonyManager/files/773096/ModsConfig.zip)
[Autosave-5.zip](https://github.com/FluffierThanThou/ColonyManager/files/773097/Autosave-5.zip)

[output_log.txt](https://github.com/FluffierThanThou/ColonyManager/files/773085/output_log.txt)

when i make favourite and save. it couldn`t load. but still great mod!

**Comment by FluffierThanThou** [comment]
this is for the Work Tab.
