### ISSUE TITLE
Crafting management won't erase finished crafting jobs

### ISSUE THREAD

**Issue by frenchiveruti** [FluffierThanThou/ColonyManager#66]
So, I decided to leave the management of my clothes to ColonyManager, and it's been running for quite a while, today, after a batch of Devilstrand harvesting, it was time to create an specific amount of dusters manually.
And That's when I ran into this:
![craftingjobhisteresis](https://cloud.githubusercontent.com/assets/1095997/23322758/3ac1caaa-fac4-11e6-9942-e28fb06d34ac.jpg)
As you can see, there's probably 45 finished tailoring jobs, that were never erased, yes, I can manually clear the list and issue what I need, but I think it's a little bug on the mod. So just reporting it.
Thanks, keep up the great work!

**Comment by sdp0et** [comment]
This occurs for me in benches other than crafting.  stoves, stonecutter's, butcher's

**Comment by Mythos** [comment]
Same here unfortunately.
Some of them aren't even done here. I had 4 jobs with 400x each to produce cotton cloth.

**Comment by elwooha6** [comment]
I've had this issue as well, happens on any bench that has a managed job.

**Comment by FluffierThanThou** [comment]
The production tab is removed A17 onwards, to be replaced with a new mod.

**Comment by frenchiveruti** [comment]
@FluffierThanThou Tell us more! You can't just say that and leave! 😞

**Comment by FluffierThanThou** [comment]
soon ™️
