### ISSUE TITLE
[Minor] Managing at Desk Takes Time, but Drafting Pawn Mid-Job Instantly Completes It

### ISSUE THREAD

**Issue by maarxx** [FluffierThanThou/ColonyManager#68]
[Minor] Managing at Desk Takes Time, but Drafting Pawn Mid-Job Instantly Completes It

**Comment by maarxx** [comment]
Might be related to how the job doesn't display a progress bar while it is being done? Probably fundamental to how the job is done.

**Comment by FluffierThanThou** [comment]
hmm, interesting. Will have a look!
