### ISSUE TITLE
Work priorities not properly restored on load

### ISSUE THREAD

**Issue by ab9rf** [FluffierThanThou/ColonyManager#70]
On reloading a saved game, work priorities are not properly restored. The values restored do not seem to have any identifiable relationship to what they were before save.

This happens quite consistently.

**Comment by maarxx** [comment]
I think you intended this for FluffierThanThou/WorkTab and not FluffierThanThou/ColonyManager

And therein, you might find it already exists as FluffierThanThou/WorkTab#49

**Comment by ab9rf** [comment]
Yes, you're entirely correct. My apologies for the misfiled report.
