### ISSUE TITLE
Manager count animals marked for hunt that have left map against target

### ISSUE THREAD

**Issue by ab9rf** [FluffierThanThou/ColonyManager#71]
Flagged a bunch of alphabeavers for hunting. They ultimately left the map in some other way, probably wandered off. The meat expected from their hunting was still counted toward quota and caused hunting to stop.

**Comment by FluffierThanThou** [comment]
hmm, they should get updated, but that might only occur when the job is running. I'll look into it!

**Comment by FluffierThanThou** [comment]
going over the code, they really should get updated. I'm going to close this as it's entirely possible I fixed this but forgot to close the issue. If you're still playing and can replicate this on A17, could you send me a save game where it's happening?
