### ISSUE TITLE
Should Consider Adult Target Before Slaughtering Juveniles

### ISSUE THREAD

**Issue by maarxx** [FluffierThanThou/ColonyManager#76]
Should Consider Adult Target Before Slaughtering Juveniles

If I have 10 Adult Males and 100 Juvenile Males, and I set the Adult Male target to 50 and the Juvenile Male target to 0, it should know to leave 40 Juveniles alive.

Currently, it slaughters all the Juveniles, leaving only the 10 Adults.

**Comment by FluffierThanThou** [comment]
yeah, no. Neither I nor the manager can infer your intent from your actions. The manager simply does what you tell it to. In this case, tell it to keep some juveniles alive.
