### ISSUE TITLE
Should Allow Different Zone for Animals Designated for Slaughter

### ISSUE THREAD

**Issue by maarxx** [FluffierThanThou/ColonyManager#77]
Should Allow Different Zone for Animals Designated for Slaughter

It would be awesome if it let me set a different Allowed Area for animals designated for Slaughter, regardless of their gender or age.

Currently I need to keep some and slaughter others within a same Gender/Age but within the manager there is no way to move just some of them to the freezer before slaughtering them.

Currently I have to move them all to the freezer and then move back those that are left.

**Comment by FluffierThanThou** [comment]
I've had some more requests for this, will see if I can squeeze it in.

**Comment by FluffierThanThou** [comment]
implemented
