### ISSUE TITLE
Game Crash, Possibly related to this mod

### ISSUE THREAD

**Issue by 47a** [FluffierThanThou/ColonyManager#80]
https://files.fm/u/t38m56f9    crash log, I was told my crash had something to do with too many jobs, not sure if it might be related to this mod, Thanks :)

**Comment by FluffierThanThou** [comment]
nope, not this mod. This mod does not alter how pawns perform jobs, it only hands them out automatically. It's therefore unlikely that this mod will cause any job related errors. 

You do have some other issue; it appears your system keeps loosing track of your 3d drivers, I have no idea what that means, but it can't be good. The actual crash appears to be memory related.
