### ISSUE TITLE
Task error

### ISSUE THREAD

**Issue by HairyMilkshakes** [FluffierThanThou/ColonyManager#85]
Hello, I found the following error in the debug log:

`Jenni started 10 jobs in 10 ticks. List: (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) , and (TakeInventory A=Thing_Kibble479703) (WaitMaintainPosture) lastJobGiver=, curJob.def=WaitMaintainPosture, curDriver=Verse.AI.JobDriver_WaitMaintainPosture Verse.Log:Error(String) Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String) Verse.AI.Pawn_JobTracker:FinalizeTick() Verse.AI.Pawn_JobTracker:JobTrackerTick() Verse.Pawn:Tick() Verse.TickList:Tick() Verse.TickManager:DoSingleTick() Verse.TickManager:TickManagerUpdate() Verse.Game:UpdatePlay() Verse.Root_Play:Update()`

Please let me know whether it is related to Colony Manager. The gameplay error is that my pawns are unable to handle animals at this time.

**Comment by FluffierThanThou** [comment]
Not related. Colony Manager _does not_ alter how pawns do jobs, or make any changes to jobs itself. All it does is automatically assign designations - anything after that is handled exactly the same as if you had manually given the orders.
