### ISSUE TITLE
Fluffy

### ISSUE THREAD

**Issue by Danomano** [FluffierThanThou/ColonyManager#99]
Hey fluffy boy, what's the deal with the construction tab? Still disabled? Any plans to re-enable it??

**Comment by Karel-Kroeze** [comment]
Hey Danomano, I replied to a similar issue by you earlier (#89). My position hasn't really changed since then.

What functionality are you looking for that isn't currently in the Improved Workbench Management mod?

**Comment by Danomano** [comment]
You're position is retarded and you should re enable the construction tab.

**Comment by FluffierThanThou** [comment]
Wow, rude. You're in my house here, so behave.
